### ISSUE TITLE
Failed to compile gcc-7.4.0 using install_gcc-7.4.0.sh script

### ISSUE THREAD

**Issue by pdineshb** [petersenna/codeviz#2]
I am running into the compile error for file cxx11-ios_failure.cc when the ./install_gcc-7.4.0.sh was executed.

Did anyone faced this problem?

make[6]: Entering directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11'
/bin/sh ../../libtool --tag CXX --tag disable-shared   --mode=compile /home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc/xgcc -shared-libgcc -B/home/testuser/Downloads/codeviz/compilers/gcc-graph/objd
ir/./gcc -nostdinc++ -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/
src/.libs -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/bin/ -B/home/testuser/gcc-graph/x86_64-pc-linux-g
nu/lib/ -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/include -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/sys-include    -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/
../libgcc -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/
libstdc++-v3/include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/libsupc++   -std=gnu++11 -prefer-pic -D_GLIBCXX_SHARED -fno-implicit-templates  -Wall -Wextra -Wwrite-strings -Wca
st-qual -Wabi  -fdiagnostics-show-location=once   -ffunction-sections -fdata-sections  -frandom-seed=cxx11-ios_failure-lt.s -g -O2 -D_GNU_SOURCE  -S ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_fail
ure.cc -o tmp-cxx11-ios_failure-lt.s
libtool: compile:  /home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc/xgcc -shared-libgcc -B/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc -nostdinc++ -L/home/testuser/Downloads/codev
iz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs -L/home/testuser/Downloads/codeviz/compiler
s/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/bin/ -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/lib/ -isystem /home/testuser/gcc-graph/x86_64-pc-l
inux-gnu/include -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/sys-include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/../libgcc -I/home/testuser/Downloads/codeviz/compilers/g
cc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include -I/home/testuser/Downloads/codeviz/
compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/libsupc++ -std=gnu++11 -D_GLIBCXX_SHARED -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -f
data-sections -frandom-seed=cxx11-ios_failure-lt.s -g -O2 -D_GNU_SOURCE -S ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_failure.cc  -fPIC -DPIC -D_GLIBCXX_SHARED
opened dep file ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_failure.cc.cdepn
libtool: compile: mv -f "cxx11-ios_failure.o" "tmp-cxx11-ios_failure-lt.o"
mv: cannot stat 'cxx11-ios_failure.o': No such file or directory
Makefile:755: recipe for target 'cxx11-ios_failure-lt.s' failed
make[6]: *** [cxx11-ios_failure-lt.s] Error 1
make[6]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11'
Makefile:641: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src'
Makefile:510: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3'
Makefile:417: recipe for target 'all' failed

are there any patches missing which will fix the compile problem?

I had to install gmp,mpfr,mpc libraries to configure the gcc-7.4.0, I think that is one thing different from the instructions.

Here is the distribution Info
:~/Downloads/codeviz/compilers$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

Any help is appreciated. Thanks

**Comment by phyzhenli** [comment]
> I am running into the compile error for file cxx11-ios_failure.cc when the ./install_gcc-7.4.0.sh was executed.
> 
> Did anyone faced this problem?
> 
> make[6]: Entering directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11'
> /bin/sh ../../libtool --tag CXX --tag disable-shared --mode=compile /home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc/xgcc -shared-libgcc -B/home/testuser/Downloads/codeviz/compilers/gcc-graph/objd
> ir/./gcc -nostdinc++ -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/
> src/.libs -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/bin/ -B/home/testuser/gcc-graph/x86_64-pc-linux-g
> nu/lib/ -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/include -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/sys-include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/
> ../libgcc -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/
> libstdc++-v3/include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/libsupc++ -std=gnu++11 -prefer-pic -D_GLIBCXX_SHARED -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wca
> st-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=cxx11-ios_failure-lt.s -g -O2 -D_GNU_SOURCE -S ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_fail
> ure.cc -o tmp-cxx11-ios_failure-lt.s
> libtool: compile: /home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc/xgcc -shared-libgcc -B/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc -nostdinc++ -L/home/testuser/Downloads/codev
> iz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs -L/home/testuser/Downloads/codeviz/compiler
> s/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/bin/ -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/lib/ -isystem /home/testuser/gcc-graph/x86_64-pc-l
> inux-gnu/include -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/sys-include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/../libgcc -I/home/testuser/Downloads/codeviz/compilers/g
> cc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include -I/home/testuser/Downloads/codeviz/
> compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/libsupc++ -std=gnu++11 -D_GLIBCXX_SHARED -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -f
> data-sections -frandom-seed=cxx11-ios_failure-lt.s -g -O2 -D_GNU_SOURCE -S ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_failure.cc -fPIC -DPIC -D_GLIBCXX_SHARED
> opened dep file ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_failure.cc.cdepn
> libtool: compile: mv -f "cxx11-ios_failure.o" "tmp-cxx11-ios_failure-lt.o"
> mv: cannot stat 'cxx11-ios_failure.o': No such file or directory
> Makefile:755: recipe for target 'cxx11-ios_failure-lt.s' failed
> make[6]: *** [cxx11-ios_failure-lt.s] Error 1
> make[6]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11'
> Makefile:641: recipe for target 'all-recursive' failed
> make[5]: *** [all-recursive] Error 1
> make[5]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src'
> Makefile:510: recipe for target 'all-recursive' failed
> make[4]: *** [all-recursive] Error 1
> make[4]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3'
> Makefile:417: recipe for target 'all' failed
> 
> are there any patches missing which will fix the compile problem?
> 
> I had to install gmp,mpfr,mpc libraries to configure the gcc-7.4.0, I think that is one thing different from the instructions.
> 
> Here is the distribution Info
> :~/Downloads/codeviz/compilers$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 18.04.4 LTS
> Release: 18.04
> Codename: bionic
> 
> Any help is appreciated. Thanks

I encounter the same question. And don't find a solution.

**Comment by hsa78** [comment]
> I am running into the compile error for file cxx11-ios_failure.cc when the ./install_gcc-7.4.0.sh was executed.
> 
> Did anyone faced this problem?
> 
> make[6]: Entering directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11'
> /bin/sh ../../libtool --tag CXX --tag disable-shared --mode=compile /home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc/xgcc -shared-libgcc -B/home/testuser/Downloads/codeviz/compilers/gcc-graph/objd
> ir/./gcc -nostdinc++ -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/
> src/.libs -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/bin/ -B/home/testuser/gcc-graph/x86_64-pc-linux-g
> nu/lib/ -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/include -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/sys-include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/
> ../libgcc -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/
> libstdc++-v3/include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/libsupc++ -std=gnu++11 -prefer-pic -D_GLIBCXX_SHARED -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wca
> st-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=cxx11-ios_failure-lt.s -g -O2 -D_GNU_SOURCE -S ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_fail
> ure.cc -o tmp-cxx11-ios_failure-lt.s
> libtool: compile: /home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc/xgcc -shared-libgcc -B/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/./gcc -nostdinc++ -L/home/testuser/Downloads/codev
> iz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src -L/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs -L/home/testuser/Downloads/codeviz/compiler
> s/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/bin/ -B/home/testuser/gcc-graph/x86_64-pc-linux-gnu/lib/ -isystem /home/testuser/gcc-graph/x86_64-pc-l
> inux-gnu/include -isystem /home/testuser/gcc-graph/x86_64-pc-linux-gnu/sys-include -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/../libgcc -I/home/testuser/Downloads/codeviz/compilers/g
> cc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu -I/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/include -I/home/testuser/Downloads/codeviz/
> compilers/gcc-graph/gcc-7.4.0/libstdc++-v3/libsupc++ -std=gnu++11 -D_GLIBCXX_SHARED -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -f
> data-sections -frandom-seed=cxx11-ios_failure-lt.s -g -O2 -D_GNU_SOURCE -S ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_failure.cc -fPIC -DPIC -D_GLIBCXX_SHARED
> opened dep file ../../../../../gcc-7.4.0/libstdc++-v3/src/c++11/cxx11-ios_failure.cc.cdepn
> libtool: compile: mv -f "cxx11-ios_failure.o" "tmp-cxx11-ios_failure-lt.o"
> mv: cannot stat 'cxx11-ios_failure.o': No such file or directory
> Makefile:755: recipe for target 'cxx11-ios_failure-lt.s' failed
> make[6]: *** [cxx11-ios_failure-lt.s] Error 1
> make[6]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11'
> Makefile:641: recipe for target 'all-recursive' failed
> make[5]: *** [all-recursive] Error 1
> make[5]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3/src'
> Makefile:510: recipe for target 'all-recursive' failed
> make[4]: *** [all-recursive] Error 1
> make[4]: Leaving directory '/home/testuser/Downloads/codeviz/compilers/gcc-graph/objdir/x86_64-pc-linux-gnu/libstdc++-v3'
> Makefile:417: recipe for target 'all' failed
> 
> are there any patches missing which will fix the compile problem?
> 
> I had to install gmp,mpfr,mpc libraries to configure the gcc-7.4.0, I think that is one thing different from the instructions.
> 
> Here is the distribution Info
> :~/Downloads/codeviz/compilers$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 18.04.4 LTS
> Release: 18.04
> Codename: bionic
> 
> Any help is appreciated. Thanks

I have the same problem. did you find a solution?

**Comment by petersenna** [comment]
@hsa78 I am sorry, but I can't help you. I used this code many years ago during my PhD and never evolved it. Back then it was already abandonware, I simply made it available on GitHub.
